on: 
  workflow_dispatch:
    inputs:
      # environment:
      #   description: "What GitHub environment are we deploying to?"
      #   required: true
      #   default: 'Preview'
      #   type: environment
      environment:
        description: "What environment are we deploying to?"
        required: true
        default: 'Preview'
        type: choice
        options: 
        - Production
        - Preview
      selected_bundle:
        description: "Which bundle are we deploying?"
        required: true
        default: 'publicdata-bundle.tar.gz'
        type: choice
        options: 
        - publicdata-bundle.tar.gz
        - publicdata-testbundle-summer2020.tar.gz
        - publicdata-testbundle-year2021.tar.gz
      selected_mock_database:
        description: "Which mock database are we deploying?"
        required: true
        default: 'database.tar.gz'
        type: choice
        options: 
        - database.tar.gz
      # concurrent_worker_limit:
      #   description: "How many workers can be ran simultaneously?"
      #   required: true
      #   default: '1'
      #   type: 'string'
      # batch_processing_mode:
      #   description: "How should the deployment scripts run?"
      #   required: true
      #   default: 'Sequential'
      #   type: choice
      #   options: 
      #   - Concurrent
      #   - Sequential

name: Deployment

jobs:
  deployment:
    name: Deployment
    runs-on: self-hosted
    #environment: ${{ inputs.environment }}
    # environment:
    #   name: ${{ inputs.environment }}
    #   url: ${{ inputs.environment == 'Production' && 'https://cougargrades.io/' || 'https://next.cougargrades.io/' }}
    # 24 hours in minutes
    #timeout-minutes: 1440
    # 72 hours in minutes
    timeout-minutes: 4320
    env:
      FIREBASE_SERVICE_ACCOUNT: ${{ (github.event.inputs.environment == 'Production' && secrets.FIREBASE_PRODUCTION_SERVICE_ACCOUNT) || secrets.FIREBASE_PREVIEW_SERVICE_ACCOUNT }}
      #BATCH_PROCESSING_MODE: ${{ github.event.inputs.batch_processing_mode }}
      CONCURRENT_WORKER_LIMIT: ${{ github.event.inputs.concurrent_worker_limit }}
      SELECTED_BUNDLE: ${{ github.event.inputs.selected_bundle }}
      SELECTED_MOCK_DATABASE: ${{ github.event.inputs.selected_mock_database }}
    steps:
      - name: We're running in the Preview Environment
        id: 'environment_check_preview'
        if: ${{ inputs.environment == 'Preview' }}
        run: echo ${{ inputs.environment }}
      - name: We're running in the Production Environment
        id: 'environment_check_production'
        if: ${{ inputs.environment == 'Production' }}
        run: echo ${{ inputs.environment }}
      - name: Checkout code
        uses: actions/checkout@master
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install + Compile
        run: |
          npm install
          npm run build

      - name: Test Firebase access
        run: node build/testAccess.js

      - name: Download latest database copy
        run: node build/downloadBundle.js

      # - name: Build local copy of the database
      #   run: node build/createMockDatabase.js

      - name: Delete database from the Cloud
        run: node build/deleteCollections.js

      - name: Upload database to the Cloud
        run: node build/uploadMockDatabase.js

      # - name: Execute first phase of patchfiles
      #   run: node build/executePatchfiles.js --just-first-phase

      # - name: Upload records from CSV data (Concurrent)
      #   if: ${{ github.event.inputs.batch_processing_mode == 'Concurrent' }}
      #   run: node build/uploadRecords.js
      
      # - name: Upload records from CSV data
      #   #if: ${{ github.event.inputs.batch_processing_mode == 'Sequential' }}
      #   run: node build/uploadRecords.js

      # - name: Execute remaining patchfiles
      #   run: node build/executePatchfiles.js
