on: 
  workflow_dispatch:
    inputs:
      environment:
        description: "What environment are we deploying to?"
        required: true
        default: 'Preview'
        type: choice
        options: 
        - Production
        - Preview
      selected_bundle:
        description: "Which bundle are we deploying?"
        required: true
        default: 'publicdata-bundle.tar.gz'
        type: choice
        options: 
        - publicdata-bundle.tar.gz
        - publicdata-testbundle-summer2020.tar.gz
        - publicdata-testbundle-year2021.tar.gz
      batch_processing_mode:
        description: "How should the deployment scripts run?"
        required: true
        default: 'Sequential'
        type: choice
        options: 
        - Concurrent
        - Sequential

name: Deployment

jobs:
  deployment:
    name: Deployment
    runs-on: self-hosted
    # 24 hours in minutes
    #timeout-minutes: 1440
    # 72 hours in minutes
    timeout-minutes: 4320
    env:
      FIREBASE_SERVICE_ACCOUNT: ${{ (github.event.inputs.environment == 'Production' && secrets.FIREBASE_PRODUCTION_SERVICE_ACCOUNT) || secrets.FIREBASE_PREVIEW_SERVICE_ACCOUNT }}
      BATCH_PROCESSING_MODE: ${{ github.event.inputs.batch_processing_mode }}
      SELECTED_BUNDLE: ${{ github.event.inputs.selected_bundle }}
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install + Compile
        run: |
          npm install
          npm run build

      - name: Test Firebase access
        run: node build/testAccess.js

      - name: Download latest public data bundle
        run: node build/downloadBundle.js

      - name: Delete existing collections
        run: node build/deleteCollections.js

      - name: Execute first phase of patchfiles
        run: node build/executePatchfiles.js --just-first-phase

      - name: Upload records from CSV data (Concurrent)
        if: ${{ github.event.inputs.batch_processing_mode == 'Concurrent' }}
        run: node build/uploadRecords.js
      
      - name: Upload records from CSV data (Sequential)
        if: ${{ github.event.inputs.batch_processing_mode == 'Sequential' }}
        run: node build/uploadRecordsSequential.js

      - name: Execute remaining patchfiles
        run: node build/executePatchfiles.js
