
on:
  workflow_dispatch:
    inputs:
      season:
        description: 'Which season are we inquiring about?'     
        required: true
        #default: 'warning' 
        type: choice
        options:
        - 'Spring'
        - 'Summer'
        - 'Fall'
      year:
        description: 'Which year are we inquiring about?'     
        required: true
        type: number
      # tags:
      #   description: 'Test scenario tags'
      #   required: false 
      #   type: boolean
      # environment:
      #   description: 'Environment to run tests against'
      #   type: environment
      #   required: true
  #schedule:
    # end of Spring,Summer,Fall semester
  #  - cron: '0 0 30 5,8,12 *'
    # end of Spring semester
    #- cron: '0 0 30 5 *'
    # end of Summer semester
    #- cron: '0 0 30 8 *'
    # end of Fall semester
    #- cron: '0 0 30 12 *'
    # * is a special character in YAML so you have to quote this string
    #- cron:  '*/10 * * * *'

name: Send Data Email

jobs:
  build:
    name: Send Data Email
    runs-on: ubuntu-latest
    steps:
      # - name: Get current date and timestamp
      #   id: timestamp
      #   run: | 
      #     CURRENTMONTH=$(date +'%m')
      #     CURRENTYEAR=$(date +'%Y')
      #     LASTYEAR=$(date --date='-1 year' +'%Y')
      #     echo "::set-output name=datestamp::$(date +'%Y-%m-%d')"
      #     echo "::set-output name=currentmonth::$CURRENTMONTH"
      #     echo "::set-output name=currentyear::$(date +'%Y')"
      #     echo "::set-output name=lastyear::$(date --date='-1 year' +'%Y')"

      #     if [ "${{ github.event.inputs.season }}" = "Fall" ]; then
      #       if [ "$CURRENTMONTH" = "12" ]; then
      #         echo "::set-output name=calculatedyear::$CURRENTYEAR"
      #       else
      #         echo "::set-output name=calculatedyear::$LASTYEAR"
      #       fi
      #     else
      #       echo "::set-output name=calculatedyear::$CURRENTYEAR"
      #     fi
      - name: Compute variables
        id: computed
        #if: github.event.schedule != '30 5 * * 1,3'
        run: |
          # TODO: calculate dynamically
          echo "SEMESTER=${{ github.event.inputs.season }} ${{ github.event.inputs.year }}" >> "$GITHUB_OUTPUT"
      - name: Send email
        uses: azure/cli@v2
        env:
          ACS_CONNECTION_STRING: ${{secrets.ACS_CONNECTION_STRING}}
          SEMESTER: ${{ steps.computed.outputs.SEMESTER }}
          MAIL_PLAINTEXT_BODY: |
            Dear Public Information Officer,
            
            Pursuant to the Texas Public Information Act, I am requesting the grade distributions by percent and/or letter grade, for every class and instructor (at both the undergraduate and graduate levels) for the ${{ env.SEMESTER }} semester at the University of Houston (University Park / main campus) and associated satellite campuses (such as UH Sugar Land).
            Please ensure the documents are FERPA compliant.
            I request that the information is in CSV format, and in digital format.
            
            Preferably in the form:

            Course Subject, Course Number, Course Title, Course Section, Term/Semester, Primary Instructor, A+, A, A-, B+, B, B-, C+, C, C-, D+, D, D-, F, W, Average Grade in GPA, S (Satisfactory), NCR (No Credit Reported).

            Please note, I have included the "S" and "NCR" fields as part of the Spring 2020 Interim Grade Policy. If including these fields is not applicable, extra work, or otherwise incompatible with your procedures, please do not include them as part of this request.
            In addition, if putting in that format is extra work, comma separated value format with the requisite information is acceptable.
            Please notify me of any expenses prior to incurring them.

            Thank you,
            Austin Jackson
            ${{secrets.MAIL_PERSONAL_INFO}}
          MAIL_TO: austinjckson@gmail.com
          MAIL_CC: austinjckson@gmail.com
          MAIL_REPLY_TO: austinjckson@gmail.com
          MAIL_SUBJECT: FOIA/PIA Request (${{ steps.timestamp.outputs.datestamp }})
        with:
          azcliversion: 2.73.0
          inlineScript: |
            az extension add --name communication
            az communication email send --connection-string $ACS_CONNECTION_STRING --sender "DoNotReply@cougargrades.io" --to $MAIL_TO --cc $MAIL_CC --reply-to $MAIL_REPLY_TO --subject $MAIL_SUBJECT --text $MAIL_PLAINTEXT_BODY
